name: First Workflow
# when will be executed. Event or events. Manually (worflow dispatch) Tab for indetation.
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
